### PR TITLE
Use Node.net to connect to pipe

### PR DESCRIPTION
**Pull request by bekopharm**
This way this can also work on Linux PC but I'm not sure if this breaks how this works on Windows PC.

Please try and give feedback!

Happy to discuss :)

### CODE REVIEW

**Comment by bekopharm** [comment]
Here is a demo snippet where I'm running the extensions X4-External-App and X4-SimPit on Linux PC: https://www.youtube.com/watch?v=suik2_baUfU

**Comment by mycumycu** [comment]
Dang, forgot about this one.
I should be able to test it this weekend.

**Comment by bekopharm** [comment]
No rush. I'm probably currently the only user anyway. It'd just be nice to point someone else to `X4-External-App` to try with my socket implementation for X4. My own extension is for simulated cockpits to get ship telemetry data and that's even more niche :upside_down_face:

**Comment by mycumycu** [comment]
Just tested it on Win11 and works fine.

Only issue is the console being like spammed with 'Connecting (...) / Disconnected (...)' output.
The 'outputMessage' method mutes the result when it doesn't differ from the previous one - but in this case it shifts from one to another:

image

**Comment by mycumycu** [comment]
> No rush. I'm probably currently the only user anyway. It'd just be nice to point someone else to `X4-External-App` to try with my socket implementation for X4. My own extension is for simulated cockpits to get ship telemetry data and that's even more niche 🙃

I will ask linux users to confirm if this version works correctly for them when released.
Good work with this PR!.

**Comment by mycumycu** [comment]
@bekopharm what about the python pipe server itself? wine? 
I'm not deeply familiar with this platform.

**Comment by bekopharm** [comment]
I can rewrite that so it does not spam stdout :)

Think my own only emits once every minute or so :thinking: 

The Linux part for the Pipe Server is different. I'm not using the Python Pipe Server at all in my fork of `sn_mod_support_apis`. Instead it's X4 itself that starts the socket|s (the NamedPipes on Windows). It's different to set up and does also require a .so (like a .dll on Windows) but I don't have to distribute this part. It comes with most distributions already and just has to be installed and put/linked in place. So the sensitive part is really coming from the distribution and not from "some website on the internet" :sweat_smile: 

Here is a very quick how-to: https://github.com/bekopharm/x4-projects/wiki/Quick-manual

Once this is in place the socket is raised e.g. in `~/.config/EgoSoft/X4/save/x4_python_host.xml` on savegame load from where X4-External-App can read from just as you're used to it.

Hoping to bring this into the official repo someday but I am really in need of more testers first. For now it's just Works On My Machine for all I know.

**Comment by mycumycu** [comment]
> Hoping to bring this into the official repo someday but I am really in need of more testers first. For now it's just Works On My Machine for all I know.

If you post on X4 EA nexus mod page to linux users for testing - I'd make such post sticky. 
This way some willing linux players could confirm it working on this platform, so it could be released afterwards.

**Comment by HalJordan** [comment]
I'm a bit late to the party, but I'm willing to try this. It looks similar to what Elite does.

I really wish EgoSoft would implement this natively. Even a simple text file like what elite does would do.

**Comment by bekopharm** [comment]
> I'm a bit late to the party, but I'm willing to try this. It looks similar to what Elite does.

I started doing this exactly how Elite does it: https://github.com/bekopharm/x4-simpit

Check this [unlisted] demo to see it in action: https://www.youtube.com/watch?v=6be--G32yHw

**Comment by bekopharm** [comment]
Should no longer spam the log @mycumycu :)

**Comment by mycumycu** [comment]
> Should no longer spam the log @mycumycu :)

Thanks @bekopharm - is this PR suitable for release? Does it work on Linux env for you without issues?

**Pull request merged**
